apiVersion: v1
kind: Service

metadata:
  name: agronotificacao-service

spec:
  type: ClusterIP

  selector:
    app: agronotificacao

  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
