apiVersion: v1
kind: Service

metadata:
  name: agronotificacao-service

spec:
  type: NodePort

  selector:
    app: agronotificacao

  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30007
